### ISSUE TITLE
MAVEN Build Failed: patient-measurements-api: There are test failures

### ISSUE THREAD

**Issue by Aperture77** [phenotips/phenotips#2915] opened 2020-11-03 23:30 UTC
Hello,

While trying to build Phenotips on my local Windows 10 computer, I encountered error during the maven build.
I simply cloned the repo and ran mvn install.

```
[ERROR] Tests run: 10, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 0.542 s <<< FAILURE! - in org.phenotips.measurements.internal.DefaultMeasurementsChartConfigurationsFactoryTest
[ERROR] simpleLoadChart(org.phenotips.measurements.internal.DefaultMeasurementsChartConfigurationsFactoryTest)  Time elapsed: 0.022 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[Weight for age, 1 to 3 year]s> but was:<[Poids selon âge, de 1 à 3 an]s>
        at org.phenotips.measurements.internal.DefaultMeasurementsChartConfigurationsFactoryTest.simpleLoadChart(DefaultMeasurementsChartConfigurationsFactoryTest.java:70)

[ERROR] loadChartWithOneSidedLabels(org.phenotips.measurements.internal.DefaultMeasurementsChartConfigurationsFactoryTest)  Time elapsed: 0.01 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[Age labels]> but was:<[Étiquettes d?âge]>
        at org.phenotips.measurements.internal.DefaultMeasurementsChartConfigurationsFactoryTest.loadChartWithOneSidedLabels(DefaultMeasurementsChartConfigurationsFactoryTest.java:105)

[ERROR] loadChartWithDefaultValues(org.phenotips.measurements.internal.DefaultMeasurementsChartConfigurationsFactoryTest)  Time elapsed: 0.005 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[Weight for age, birth to 20 year]s> but was:<[Poids selon l'âge, de la naissance à 20 an]s>
        at org.phenotips.measurements.internal.DefaultMeasurementsChartConfigurationsFactoryTest.loadChartWithDefaultValues(DefaultMeasurementsChartConfigurationsFactoryTest.java:92)

[ERROR] loadChartWithBrokenValues(org.phenotips.measurements.internal.DefaultMeasurementsChartConfigurationsFactoryTest)  Time elapsed: 0.028 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[Weight] (kg)> but was:<[Poids] (kg)>
        at org.phenotips.measurements.internal.DefaultMeasurementsChartConfigurationsFactoryTest.loadChartWithBrokenValues(DefaultMeasurementsChartConfigurationsFactoryTest.java:149)

[INFO] Running org.phenotips.measurements.script.MeasurementsScriptServiceTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.173 s - in org.phenotips.measurements.script.MeasurementsScriptServiceTest
[INFO] Running org.phenotips.measurements.internal.MeasurementAgeUpdaterTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.511 s - in org.phenotips.measurements.internal.MeasurementAgeUpdaterTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   DefaultMeasurementsChartConfigurationsFactoryTest.loadChartWithBrokenValues:149 expected:<[Weight] (kg)> but was:<[Poids] (kg)>
[ERROR]   DefaultMeasurementsChartConfigurationsFactoryTest.loadChartWithDefaultValues:92 expected:<[Weight for age, birth to 20 year]s> but was:<[Poids selon l'âge, de la naissance à 20 an]s>
[ERROR]   DefaultMeasurementsChartConfigurationsFactoryTest.loadChartWithOneSidedLabels:105 expected:<[Age labels]> but was:<[Étiquettes d?âge]>
[ERROR]   DefaultMeasurementsChartConfigurationsFactoryTest.simpleLoadChart:70 expected:<[Weight for age, 1 to 3 year]s> but was:<[Poids selon âge, de 1 à 3 an]s>
[INFO]
[ERROR] Tests run: 102, Failures: 4, Errors: 0, Skipped: 1
```

And the final Build failure:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:06 min
[INFO] Finished at: 2020-11-04T00:22:37+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project patient-measurements-api: There are test failures.
[ERROR]
[ERROR] Please refer to D:\Program Files (x86)\phenotips\components\patient-measurements\api\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :patient-measurements-api
```
My MVN & Java informations:
```
D:\Program Files (x86)\phenotips>mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files (x86)\apache-maven-3.6.3\bin\..
Java version: 1.8.0_271, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_271\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

This is the same error as https://github.com/phenotips/phenotips/issues/2913 opened 25 days ago.
Any Ideas where this could come from ?

Thanks !

**Comment by buske** [comment] 2020-11-04 20:15
Hi @Aperture77, thank you very much for reporting. This appears to be the same issue as #2913, which has helped identify the cause. I'm going to close this as a duplicate and then reply in that issue.

**Closed by buske** 2020-11-04 20:15 UTC
