### ISSUE TITLE
Browsing the HPO ontology doesn't work correctly

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/phenotips#1498] opened 2015-03-16 20:36 UTC
Opens the wrong term, and seems to be extremely slow.

**Comment by antonkatz** [comment] 2015-03-17 13:03
I think this is a duplicate of https://github.com/phenotips/phenotips/issues/1485#issuecomment-81946693

**Comment by sdumitriu** [comment] 2015-03-17 13:19
Hm, this doesn't happen anymore, I think it was a bad internet connection.

**Closed** 2015-03-25 02:41 UTC
Labels: bug, cannot reproduce, ontologies
