### ISSUE TITLE
Growth charts should cite data sources/processing method

### ISSUE THREAD

**Issue by buske** [phenotips/phenotips#1523] opened 2015-03-28 19:57 UTC
Strongly suggest adding a note at the bottom of every growth chart describing the source(s) of the underlying data, and any modifications or caveats that come with it (e.g. only from healthy individuals).

A similar, brief, more general disclaimer could be added to the growth chart section as well.

**Comment by sdumitriu** [comment] 2015-03-28 22:46
Duplicate of #1335

**Closed by sdumitriu** 2015-03-28 22:46 UTC
Labels: duplicate, measurements and growth charts, UI
