### ISSUE TITLE
BMI calculations do not seem accurate (especially for new borns)

### ISSUE THREAD

**Issue by mjshepherd** [phenotips/phenotips#1433] opened 2015-02-12 22:41 UTC
Open a patient record and set age to today
Go to measurements and set weight to 4kg and height to 49.9cm (50th percentile for both)
BMI is in the 97th percentile

**Comment by marta-** [comment] 2015-07-23 17:11
Can't reproduce this. 4kg is definitely not 50th percentile for birth weight. Possibly fixed by #652.

**Closed by marta-** 2015-07-23 17:11 UTC
