### ISSUE TITLE
Prenatal growth parameters should be mutually exclusive.

### ISSUE THREAD

**Issue by tmarathe** [phenotips/phenotips#1679] opened 2015-05-26 15:39 UTC
I created a test patient and was able to set the 'Abnormal birth weight' field to both 'Small for gestational age (<-2SD)' and 'Large for gestational age (>+2SD)' when these options should be exclusive of each other.

Similarly for 'Abnormal birth length'.

**Comment by sdumitriu** [comment] 2015-05-27 02:28
Duplicate of #346

**Closed by sdumitriu** 2015-05-27 02:28 UTC
Labels: duplicate
