### ISSUE TITLE
Free text phenotypes are lining up side by side

### ISSUE THREAD

**Issue by bgallinger** [phenotips/phenotips#1816] opened 2015-07-10 20:34 UTC
![image](https://cloud.githubusercontent.com/assets/8963190/8628471/56c3ced8-2721-11e5-958a-7784b17ef26c.png)

This seems unusual.

**Comment by danielpgross** [comment] 2015-07-10 20:45
Duplicate of #1812

**Closed** 2015-07-10 21:55 UTC
Labels: duplicate
