### ISSUE TITLE
Suggest dialogs should hide when they loose focus

### ISSUE THREAD

**Issue by meatcar** [phenotips/phenotips#1549] opened 2015-04-07 16:36 UTC
Currently, dismissing the Phenotype Search & Suggest dialog is only possible by only clicking the "hide suggestion" links at the top and bottom corners of the dialog.

It should instead behave like a proper modal, and be dismissed when any other part of the page is clicked (i.e. the dialog looses focus). When clicking back on the search box, the dialog should pop back up (it doesn't now). This will move Phenotips closer to being well-behaved on mobile, as well as improve the UI/UX.

![capture](https://cloud.githubusercontent.com/assets/191622/7028141/f327691e-dd21-11e4-9a80-147bbb67364c.PNG)

**Comment by mjshepherd** [comment] 2015-04-10 15:41
This behaviour should also be present in other suggest dialogs. Such as the patient search or gene symbol suggestions.

**Comment by allasm** [comment] 2015-04-10 16:52
This should be very easy to do as this is the way phenotype/gene suggest dialogs work in pedigree editor

**Comment by buske** [comment] 2015-04-12 20:29
Duplicate of #1490, but will close the other as it is not as thorough.

**Closed** 2015-06-11 17:43 UTC
Labels: phenotips, UI, UX, widgets
